In [15]:
import pdblp
import pandas as pd
import math
import matplotlib.pyplot as plt
from helpers import *

In [16]:
con = pdblp.BCon(timeout=50000)
con.start()

### Dates Range

In [17]:
intermediate_dates = get_date_range(START_DATE,TODAY_DATE)
#small_intermediate_dates = [elem.strftime("%Y%m%d") for elem in pd.date_range(start='20190101',end=TODAY_DATE)]
#intermediate_dates = intermediate_dates[::-1]
print('Number of days studied :',len(intermediate_dates))

Number of days studied : 3498

# MACROS

### US Purchasing Managers Index

The economic situation is important to interest rates. When the economy is booming and there is a high demand for funds, the price of borrowing money goes up, leading to increasing interest rates. Conversely in economic recessions, there is downward pressure on interest rates.
In this context, the PMI is an index that summarizes whether market conditions, as viewed by purchasing managers, are expanding, staying the same, or contracting. 

It is a monthly released indicator, we will therefore consider that the value of the index is the same for all days of the month until the next release.

In [18]:
PMI_df = con.bdh('NAPMPMI Index','PX_LAST',START_DATE,TODAY_DATE,elms=[('nonTradingDayFillOption','NON_TRADING_WEEKDAYS')])
PMI_df.columns=['PMI']
PMI_df.to_csv('PMI.csv')
PMI_df

             PMI
date
2010-01-01  55.8
2010-01-04  55.8
2010-01-05  55.8
2010-01-06  55.8
2010-01-07  55.8
2010-01-08  55.8
2010-01-11  55.8
2010-01-12  55.8
2010-01-13  55.8
2010-01-14  55.8
2010-01-15  55.8
2010-01-18  55.8
2010-01-19  55.8
2010-01-20  55.8
2010-01-21  55.8
2010-01-22  55.8
2010-01-25  55.8
2010-01-26  55.8
2010-01-27  55.8
2010-01-28  55.8
2010-01-29  55.8
2010-01-31  56.3
2010-02-01  56.3
2010-02-02  56.3
2010-02-03  56.3
2010-02-04  56.3
2010-02-05  56.3
2010-02-08  56.3
2010-02-09  56.3
2010-02-10  56.3
...          ...
2019-06-20  52.1
2019-06-21  52.1
2019-06-24  52.1
2019-06-25  52.1
2019-06-26  52.1
2019-06-27  52.1
2019-06-28  52.1
2019-06-30  51.7
2019-07-01  51.7
2019-07-02  51.7
2019-07-03  51.7
2019-07-04  51.7
2019-07-05  51.7
2019-07-08  51.7
2019-07-09  51.7
2019-07-10  51.7
2019-07-11  51.7
2019-07-12  51.7
2019-07-15  51.7
2019-07-16  51.7
2019-07-17  51.7
2019-07-18  51.7
2019-07-19  51.7
2019-07-22  51.7
2019-07-23  51.7
2019-07-24  51.7
2019-07-25  51.7
2019-07-26  51.7
2019-07-29  51.7
2019-07-30  51.7

[2531 rows x 1 columns]

### US Unemployment Rate

Unemployment is another indicator of the financial health of a country. It is a lagging indicator, meaning that it generally rises or falls in the wake of changing economic conditions, rather than anticipating them. However, we will still consider it as one of our features because it is closely monitored by every investor.

It is a monthly released indicator, we will therefore consider that the value of the index is the same for all days of the month until the next release.

In [19]:
Unemployment_rate_df = con.bdh('USURTOT Index','Last price',START_DATE,TODAY_DATE,elms=[('nonTradingDayFillOption','NON_TRADING_WEEKDAYS')])
Unemployment_rate_df.columns=['UNEMPLOYMENT']
Unemployment_rate_df.to_csv('Unemployment_rate.csv')
Unemployment_rate_df

            UNEMPLOYMENT
date
2010-01-01           9.9
2010-01-04           9.9
2010-01-05           9.9
2010-01-06           9.9
2010-01-07           9.9
2010-01-08           9.9
2010-01-11           9.9
2010-01-12           9.9
2010-01-13           9.9
2010-01-14           9.9
2010-01-15           9.9
2010-01-18           9.9
2010-01-19           9.9
2010-01-20           9.9
2010-01-21           9.9
2010-01-22           9.9
2010-01-25           9.9
2010-01-26           9.9
2010-01-27           9.9
2010-01-28           9.9
2010-01-29           9.9
2010-01-31           9.8
2010-02-01           9.8
2010-02-02           9.8
2010-02-03           9.8
2010-02-04           9.8
2010-02-05           9.8
2010-02-08           9.8
2010-02-09           9.8
2010-02-10           9.8
...                  ...
2019-06-20           3.6
2019-06-21           3.6
2019-06-24           3.6
2019-06-25           3.6
2019-06-26           3.6
2019-06-27           3.6
2019-06-28           3.6
2019-06-30           3.7
2019-07-01           3.7
2019-07-02           3.7
2019-07-03           3.7
2019-07-04           3.7
2019-07-05           3.7
2019-07-08           3.7
2019-07-09           3.7
2019-07-10           3.7
2019-07-11           3.7
2019-07-12           3.7
2019-07-15           3.7
2019-07-16           3.7
2019-07-17           3.7
2019-07-18           3.7
2019-07-19           3.7
2019-07-22           3.7
2019-07-23           3.7
2019-07-24           3.7
2019-07-25           3.7
2019-07-26           3.7
2019-07-29           3.7
2019-07-30           3.7

[2531 rows x 1 columns]

### Consumer Price Index

Inflation has a key role in determining the price of bonds.

Indeed, when inflation gets higher the Fed has a tendency to increase interest rates to slow down the economy which results in higher bond prices. In the opposite scenario, the Fed would lower interest rates to stimulate growth resulting in a decrease of bond price.

The Consumer Price Index (CPI) is a measure that examines the weighted average of prices of a basket of consumer goods and services, such as transportation, food, and medical care. This index is one of the measures of inflation, it is by far the most looked at indicator.

In [20]:
CPI_df = con.bdh('CPI YOY Index','Last price',START_DATE,TODAY_DATE,elms=[('nonTradingDayFillOption','NON_TRADING_WEEKDAYS')])
CPI_df.columns=['CPI']
CPI_df.to_csv('CPI.csv')
CPI_df

            CPI
date
2010-01-01  2.7
2010-01-04  2.7
2010-01-05  2.7
2010-01-06  2.7
2010-01-07  2.7
2010-01-08  2.7
2010-01-11  2.7
2010-01-12  2.7
2010-01-13  2.7
2010-01-14  2.7
2010-01-15  2.7
2010-01-18  2.7
2010-01-19  2.7
2010-01-20  2.7
2010-01-21  2.7
2010-01-22  2.7
2010-01-25  2.7
2010-01-26  2.7
2010-01-27  2.7
2010-01-28  2.7
2010-01-29  2.7
2010-01-31  2.6
2010-02-01  2.6
2010-02-02  2.6
2010-02-03  2.6
2010-02-04  2.6
2010-02-05  2.6
2010-02-08  2.6
2010-02-09  2.6
2010-02-10  2.6
...         ...
2019-06-20  1.8
2019-06-21  1.8
2019-06-24  1.8
2019-06-25  1.8
2019-06-26  1.8
2019-06-27  1.8
2019-06-28  1.8
2019-06-30  1.6
2019-07-01  1.6
2019-07-02  1.6
2019-07-03  1.6
2019-07-04  1.6
2019-07-05  1.6
2019-07-08  1.6
2019-07-09  1.6
2019-07-10  1.6
2019-07-11  1.6
2019-07-12  1.6
2019-07-15  1.6
2019-07-16  1.6
2019-07-17  1.6
2019-07-18  1.6
2019-07-19  1.6
2019-07-22  1.6
2019-07-23  1.6
2019-07-24  1.6
2019-07-25  1.6
2019-07-26  1.6
2019-07-29  1.6
2019-07-30  1.6

[2531 rows x 1 columns]

### Philly Fed Survey

The Philadelphia Federal Index (or Philly Fed Survey) is a regional federal-reserve-bank index measuring changes in business growth.

When the index is above zero, it indicates factory-sector growth, and when below zero, it indicates contraction. The intention of the survey is to provide a snapshot of current manufacturing activity in this region, as well as provide a short term forecast of manufacturing conditions in the area, which may provide an indication of conditions throughout the United States.

In [21]:
Philly_Fed_df = con.bdh('OUTFGAF Index','Last price',START_DATE,TODAY_DATE,elms=[('nonTradingDayFillOption','NON_TRADING_WEEKDAYS')])
Philly_Fed_df.columns=['Philly_Fed']
Philly_Fed_df.to_csv('Philly_Fed.csv')
Philly_Fed_df

            Philly_Fed
date
2010-01-01        16.5
2010-01-04        16.5
2010-01-05        16.5
2010-01-06        16.5
2010-01-07        16.5
2010-01-08        16.5
2010-01-11        16.5
2010-01-12        16.5
2010-01-13        16.5
2010-01-14        16.5
2010-01-15        16.5
2010-01-18        16.5
2010-01-19        16.5
2010-01-20        16.5
2010-01-21        16.5
2010-01-22        16.5
2010-01-25        16.5
2010-01-26        16.5
2010-01-27        16.5
2010-01-28        16.5
2010-01-29        16.5
2010-01-31        12.9
2010-02-01        12.9
2010-02-02        12.9
2010-02-03        12.9
2010-02-04        12.9
2010-02-05        12.9
2010-02-08        12.9
2010-02-09        12.9
2010-02-10        12.9
...                ...
2019-06-20        16.6
2019-06-21        16.6
2019-06-24        16.6
2019-06-25        16.6
2019-06-26        16.6
2019-06-27        16.6
2019-06-28        16.6
2019-06-30         0.3
2019-07-01         0.3
2019-07-02         0.3
2019-07-03         0.3
2019-07-04         0.3
2019-07-05         0.3
2019-07-08         0.3
2019-07-09         0.3
2019-07-10         0.3
2019-07-11         0.3
2019-07-12         0.3
2019-07-15         0.3
2019-07-16         0.3
2019-07-17         0.3
2019-07-18         0.3
2019-07-19         0.3
2019-07-22         0.3
2019-07-23         0.3
2019-07-24         0.3
2019-07-25         0.3
2019-07-26         0.3
2019-07-29         0.3
2019-07-30         0.3

[2531 rows x 1 columns]

### LIBOR US 1 month

A major factor in interest rates changes is the monetary policy of central banks. For example, the Fed increases or decreases the Fed Funds rate - the rate for lending money to other banks - according to the economic conditions. 

In this context, the Libor, which is an average of the interest rate on deposits traded between banks, is a good reflection of changes in the Fed Funds.

It also has the advantage of having a daily market-driven fixing.

In [22]:
Libor_df = con.bdh('US0001M Index','Last price',START_DATE,TODAY_DATE,elms=[('nonTradingDayFillOption','NON_TRADING_WEEKDAYS')])
Libor_df.columns=['Libor']
Libor_df.to_csv('Libor.csv')
Libor_df

              Libor
date
2010-01-01  0.23094
2010-01-04  0.23344
2010-01-05  0.23344
2010-01-06  0.23219
2010-01-07  0.23125
2010-01-08  0.23313
2010-01-11  0.23313
2010-01-12  0.23313
2010-01-13  0.23313
2010-01-14  0.23313
2010-01-15  0.23313
2010-01-18  0.23063
2010-01-19  0.23063
2010-01-20  0.23063
2010-01-21  0.23063
2010-01-22  0.23063
2010-01-25  0.23063
2010-01-26  0.23063
2010-01-27  0.23063
2010-01-28  0.22875
2010-01-29  0.22906
2010-02-01  0.22906
2010-02-02  0.23094
2010-02-03  0.22906
2010-02-04  0.22844
2010-02-05  0.22844
2010-02-08  0.22844
2010-02-09  0.22844
2010-02-10  0.22844
2010-02-11  0.23063
...             ...
2019-06-19  2.38338
2019-06-20  2.40363
2019-06-21  2.40438
2019-06-24  2.40175
2019-06-25  2.40413
2019-06-26  2.40238
2019-06-27  2.40238
2019-06-28  2.39800
2019-07-01  2.38775
2019-07-02  2.37950
2019-07-03  2.36000
2019-07-04  2.36413
2019-07-05  2.36650
2019-07-08  2.37938
2019-07-09  2.36863
2019-07-10  2.36913
2019-07-11  2.32500
2019-07-12  2.33200
2019-07-15  2.31413
2019-07-16  2.30038
2019-07-17  2.29788
2019-07-18  2.27150
2019-07-19  2.26113
2019-07-22  2.26913
2019-07-23  2.26600
2019-07-24  2.26175
2019-07-25  2.24113
2019-07-26  2.23700
2019-07-29  2.23438
2019-07-30  2.22975

[2498 rows x 1 columns]

### Commodity research Bureau Index

The price of commodities can be a good leading indicator of inflation as it can be a store of value for investors in times of inflation.

The CRB index may be a better indicator than the price of gold. It reflects the prices of futures contracts for 21 commodities and is updated continously throughout the business day as commodity futures prices fluctuate.

In [23]:
Commodity_index_df = con.bdh('CRB RIND Index','Last price',START_DATE,TODAY_DATE,elms=[('nonTradingDayFillOption','NON_TRADING_WEEKDAYS')])
Commodity_index_df.columns=['Commodity_Index']
Commodity_index_df.to_csv('Commodity_index.csv')
Commodity_index_df

            Commodity_Index
date
2010-01-01           483.49
2010-01-04           494.19
2010-01-05           493.66
2010-01-06           494.10
2010-01-07           495.44
2010-01-08           498.36
2010-01-11           498.92
2010-01-12           497.39
2010-01-13           496.69
2010-01-14           496.97
2010-01-15           495.51
2010-01-18           495.51
2010-01-19           494.87
2010-01-20           494.87
2010-01-21           494.90
2010-01-22           492.16
2010-01-25           492.47
2010-01-26           490.35
2010-01-27           488.92
2010-01-28           479.15
2010-01-29           474.96
2010-02-01           471.27
2010-02-02           469.26
2010-02-03           469.44
2010-02-04           468.11
2010-02-05           465.89
2010-02-08           463.23
2010-02-09           469.26
2010-02-10           471.49
2010-02-11           474.98
...                     ...
2019-06-19           456.20
2019-06-20           455.50
2019-06-21           454.59
2019-06-24           455.46
2019-06-25           456.78
2019-06-26           456.03
2019-06-27           454.66
2019-06-28           455.22
2019-07-01           454.68
2019-07-02           450.97
2019-07-03           452.72
2019-07-04           452.72
2019-07-05           451.03
2019-07-08           450.43
2019-07-09           446.42
2019-07-10           448.08
2019-07-11           448.70
2019-07-12           448.55
2019-07-15           449.67
2019-07-16           448.92
2019-07-17           448.94
2019-07-18           448.18
2019-07-19           449.58
2019-07-22           449.37
2019-07-23           449.09
2019-07-24           450.75
2019-07-25           450.17
2019-07-26           449.59
2019-07-29           450.29
2019-07-30           447.46

[2498 rows x 1 columns]

### Yield spread 3M 10Y

The yield curve is a rigorously monitored recession signal because it gives a view of how investors are weighing short-term versus long-term investments and what kind of rate environment they're expecting to see.

In this context we can use the spread between three-month and 10-year Treasurys as an indicator of recessions.

In [24]:
Spread_df = con.bdh('USYC3M10 Index','Last price',START_DATE,TODAY_DATE)
Spread_df.columns=['Spread']
Spread_df.to_csv('Spread.csv')
Spread_df

             Spread
date
2010-01-01  377.610
2010-01-04  375.762
2010-01-05  369.684
2010-01-06  376.968
2010-01-07  377.681
2010-01-08  378.706
2010-01-11  379.466
2010-01-12  366.916
2010-01-13  373.903
2010-01-14  368.437
2010-01-15  361.955
2010-01-18  361.760
2010-01-19  364.519
2010-01-20  359.867
2010-01-21  354.413
2010-01-22  356.039
2010-01-25  357.974
2010-01-26  355.483
2010-01-27  357.579
2010-01-28  356.230
2010-01-29  351.226
2010-02-01  356.283
2010-02-02  355.016
2010-02-03  361.439
2010-02-04  351.848
2010-02-05  347.710
2010-02-08  346.731
2010-02-09  354.028
2010-02-10  358.715
2010-02-11  362.186
...             ...
2019-06-19  -14.621
2019-06-20  -10.762
2019-06-21   -6.111
2019-06-24   -9.813
2019-06-25  -14.100
2019-06-26  -10.214
2019-06-27  -12.971
2019-06-28   -9.457
2019-07-01   -9.356
2019-07-02  -22.135
2019-07-03  -25.814
2019-07-04  -25.814
2019-07-05  -18.912
2019-07-08  -18.807
2019-07-09  -18.604
2019-07-10  -11.769
2019-07-11   -0.514
2019-07-12   -1.556
2019-07-15   -4.864
2019-07-16   -4.908
2019-07-17   -7.818
2019-07-18   -0.907
2019-07-19   -1.625
2019-07-22   -3.003
2019-07-23    2.967
2019-07-24   -5.481
2019-07-25   -2.417
2019-07-26   -4.990
2019-07-29   -4.225
2019-07-30   -1.663

[2497 rows x 1 columns]

### Interest rates

In [25]:
interest_rates_df = con.bdh('FDTR Index','Last price',START_DATE,TODAY_DATE)
interest_rates_df.columns=['Interest_Rates']
interest_rates_df.to_csv('interest_rates.csv')
interest_rates_df

            Interest_Rates
date
2010-01-04            0.25
2010-01-05            0.25
2010-01-06            0.25
2010-01-07            0.25
2010-01-08            0.25
2010-01-11            0.25
2010-01-12            0.25
2010-01-13            0.25
2010-01-14            0.25
2010-01-15            0.25
2010-01-19            0.25
2010-01-20            0.25
2010-01-21            0.25
2010-01-22            0.25
2010-01-25            0.25
2010-01-26            0.25
2010-01-27            0.25
2010-01-28            0.25
2010-01-29            0.25
2010-02-01            0.25
2010-02-02            0.25
2010-02-03            0.25
2010-02-04            0.25
2010-02-05            0.25
2010-02-08            0.25
2010-02-09            0.25
2010-02-10            0.25
2010-02-11            0.25
2010-02-12            0.25
2010-02-16            0.25
...                    ...
2019-06-19            2.50
2019-06-20            2.50
2019-06-21            2.50
2019-06-24            2.50
2019-06-25            2.50
2019-06-26            2.50
2019-06-27            2.50
2019-06-28            2.50
2019-07-01            2.50
2019-07-02            2.50
2019-07-03            2.50
2019-07-04            2.50
2019-07-05            2.50
2019-07-08            2.50
2019-07-09            2.50
2019-07-10            2.50
2019-07-11            2.50
2019-07-12            2.50
2019-07-15            2.50
2019-07-16            2.50
2019-07-17            2.50
2019-07-18            2.50
2019-07-19            2.50
2019-07-22            2.50
2019-07-23            2.50
2019-07-24            2.50
2019-07-25            2.50
2019-07-26            2.50
2019-07-29            2.50
2019-07-30            2.50

[2475 rows x 1 columns]

In [26]:
#Aggregation of features into a single df
MACRO_df = PMI_df.join(CPI_df,how='outer').join(Unemployment_rate_df,how='outer').join(Spread_df,how='outer').\
join(Commodity_index_df,how='outer').join(Libor_df,how='outer').join(interest_rates_df,how='outer').\
join(Philly_Fed_df,how='outer')

for col in list(MACRO_df.columns):
    MACRO_df[col] = MACRO_df[col].astype(float)

MACRO_df = MACRO_df.dropna()
#Creating CSV
MACRO_df.to_csv('MACROS.csv')